services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_DATABASE: votingsystem
      TARGET_PDB: votingsystem
      ORACLE_PASSWORD: votingsystem
      APP_USER: dev_db_user
      APP_USER_PASSWORD: dev_db_password
    volumes:
      - oracle-data:/opt/oracle/oradata

  kafka:
    image: bitnami/kafka:3.5.1  # Imagem oficial do Kafka com suporte a KRaft
    container_name: kafka-kraft
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CFG_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 1
      KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE: CreateTime
      KAFKA_CFG_NUM_PARTITIONS: 1
    volumes:
      - kafka-data:/bitnami/kafka/data
    command:
      - sh
      - -c
      - |
        if [ ! -f /bitnami/kafka/data/meta.properties ]; then
          kafka-storage.sh format --ignore-formatted --cluster-id $(kafka-storage.sh random-uuid) --config /opt/bitnami/kafka/config/kraft/server.properties;
        fi &&
        kafka-server-start.sh /opt/bitnami/kafka/config/kraft/server.properties

volumes:
  oracle-data:
  kafka-data: