application:
  title: API Voting System
  version: v1.0

spring:
  application:
    name: voting-system
  threads:
    virtual:
      enabled: true
  cloud:
    stream:
      bindings:
        producer-create-user:
          destination: create-user
        producer-start-vote-session:
          destination: start-vote-session
        producer-end-vote-session:
          destination: end-vote-session
        producer-user-vote:
          destination: user-vote
logging:
  level:
    root: INFO