spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
  datasource:
    url: jdbc:oracle:thin:@oracle-db/votingsystem
    username: dev_db_user
    password: dev_db_password
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
  
  flyway:
    enabled: true

app:
  cpf-validator:
    url: "https://api.invertexto.com/v1"
    token: "16307|QoPiisj5gPWdwxD0mXQ77ZwYV0CgfmRq"