spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/votingsystem
    username: dev_db_user
    password: dev_db_password
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
  
  flyway:
    enabled: true